version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=sdfefnkuUJOU#HiNDIOhddklfnO)22#H
      - NAME=postgres
      - DB=postgres
      - PASSWORD=postgres
      - DJANGO_DEBUG=1
    ports:
      - "8000:8000"
    depends_on:
      - db
