# Generated by Django 3.0.7 on 2020-10-17 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_and_answer', '0005_auto_20200501_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes_down',
            field=models.ManyToManyField(blank=True, related_name='user_votes_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='votes_up',
            field=models.ManyToManyField(blank=True, related_name='user_votes_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
