# Generated by Django 3.0.7 on 2020-10-17 17:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_and_answer', '0006_auto_20201017_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='votes_down',
            field=models.ManyToManyField(blank=True, related_name='user_votes_answer_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='votes_up',
            field=models.ManyToManyField(blank=True, related_name='user_votes_answer_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
